remote: true

experienceLevel:
 internship: false
 entry: false
 associate: false
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: false
 part-time: false
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: false
 month: true
 week: false
 24 hours: false

positions:
  - Customer Analytics Chemist 3
  - Chemist 3
  - Chemist 2
  - Chemist 1
  - Chemist

locations:
  - Clover SC, 29710

distance: 35

companyBlacklist:
  - Company1
  - Company2

titleBlacklist:
  - word1
  - word2
